#ifndef CISC_INSTRUCTION_SET_SIMULATOR_DECODEINSTRUCTION_H
#define CISC_INSTRUCTION_SET_SIMULATOR_DECODEINSTRUCTION_H



class DecodeInstruction {

};



#endif //CISC_INSTRUCTION_SET_SIMULATOR_DECODEINSTRUCTION_H
