#ifndef CISC_INSTRUCTION_SET_SIMULATOR_EXECUTEINSTRUCTION_H
#define CISC_INSTRUCTION_SET_SIMULATOR_EXECUTEINSTRUCTION_H



class Execute {

};



#endif //CISC_INSTRUCTION_SET_SIMULATOR_EXECUTEINSTRUCTION_H
