#ifndef CISC_INSTRUCTION_SET_SIMULATOR_INSTRUCTIONFETCH_H
#define CISC_INSTRUCTION_SET_SIMULATOR_INSTRUCTIONFETCH_H



class InstructionFetch {

};



#endif //CISC_INSTRUCTION_SET_SIMULATOR_INSTRUCTIONFETCH_H
